import fs from 'fs'
import path from 'path'
import type { Agent, AgentContext, AgentResult } from './types.js'
import { readMasterSheet, localDateStr } from './data.js'
import { buildEvent } from './logger.js'

export const crmEvening: Agent = {
  id: 'gc-crm-evening',
  name: 'Evening Recon',

  async run(ctx: AgentContext): Promise<AgentResult> {
    const summary: Record<string, any> = { reconciliation_complete: true, date: ctx.now.toISOString(), errors: [] }
    const events = []
    const errors: string[] = []

    try {
      const leads = readMasterSheet(ctx.dataDir)
      const todayStr = localDateStr(ctx.now, ctx.timezone)
      const now = ctx.now.getTime()
      const staleHours = ctx.config?.follow_up?.stale_hours || 48

      const stale = leads.filter((l: any) => {
        if (l.type === 'client') return false
        if (!l.last_action_date) return false
        return (now - new Date(l.last_action_date).getTime()) / 36e5 > staleHours
      })

      const changedToday = leads.filter((l: any) => {
        if (!l.last_action_date) return false
        return l.last_action_date.startsWith(todayStr)
      })

      const lines = [
        `*Evening Reconciliation — ${todayStr}*`,
        '',
        `*Changes Today*`,
        `• Leads updated: ${changedToday.length}`,
        ...changedToday.slice(0, 15).map((l: any) => `• ${l.name}: ${l.status} (${l.last_action || ''})`),
        '',
        `*Stale Leads (> ${staleHours}h)*`,
        `• Count: ${stale.length}`,
        ...stale.slice(0, 10).map((l: any) => `• ${l.name} — ${l.status} — last action: ${l.last_action || 'none'}`),
        '',
        `_Generated by ${this.name} at ${ctx.now.toISOString()}_`,
      ]

      const dir = path.join(ctx.dataDir, 'reports', 'daily')
      fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(path.join(dir, `${todayStr}-evening.md`), lines.join('\n'))

      // Post to Slack if configured
      if (ctx.slack.isEnabled()) {
        const channel = ctx.config?.slack?.channels?.sales?.id || ctx.config?.slack?.channels?.ai_assistant?.id
        if (channel) {
          const result = await ctx.slack.postMessage({ channel, text: lines.join('\n') })
          summary.slack_posted = result.ok
          if (!result.ok) errors.push(`Slack post failed: ${result.error}`)
        }
      }

      events.push(buildEvent(this.id, 'run_summary', summary))
    } catch (err: any) {
      errors.push(err.message)
      summary.errors.push(err.message)
    }

    return { success: errors.length === 0, summary, errors, events }
  },
}
