import fs from 'fs'
import path from 'path'
import type { Agent, AgentContext, AgentResult } from './types.js'
import { readMasterSheet, readJSONL, localDateStr } from './data.js'
import { buildEvent } from './logger.js'

export const crmMorning: Agent = {
  id: 'gc-crm-morning',
  name: 'Morning Briefing',

  async run(ctx: AgentContext): Promise<AgentResult> {
    const summary: Record<string, any> = { briefing_generated: true, date: ctx.now.toISOString(), errors: [] }
    const events = []
    const errors: string[] = []

    try {
      const leads = readMasterSheet(ctx.dataDir)
      const todayStr = localDateStr(ctx.now, ctx.timezone)
      const hot = leads.filter((l: any) => l.score === 'HOT' && l.type !== 'client')
      const booked = leads.filter((l: any) => l.status === 'booked')
      const proposals = leads.filter((l: any) => l.status === 'proposal_sent')
      const recentEvents = readJSONL(ctx.dataDir, 'agent-events.jsonl').slice(-50)

      const lines = [
        `*Morning Briefing — ${todayStr}*`,
        '',
        `*Pipeline Snapshot*`,
        `• Total leads: ${leads.filter((l: any) => l.type !== 'client').length}`,
        `• HOT leads: ${hot.length}`,
        `• Calls booked today: ${booked.length}`,
        `• Proposals out: ${proposals.length}`,
        '',
        `*Today's Calls*`,
        ...booked.map((l: any) => `• ${l.name} (${l.company || 'no company'}) — ${l.next_call_date || 'TBD'}`),
        booked.length === 0 ? '• No calls scheduled.' : '',
        '',
        `*HOT Leads Requiring Attention*`,
        ...hot.slice(0, 10).map((l: any) => `• ${l.name} — ${l.status} — ${l.last_action || 'no action'}`),
        '',
        `_Generated by ${this.name} at ${ctx.now.toISOString()}_`,
      ]

      const markdownLines = lines.map(l => l.replace(/\*/g, '*'))
      const dir = path.join(ctx.dataDir, 'reports', 'daily')
      fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(path.join(dir, `${todayStr}-morning.md`), markdownLines.join('\n'))

      // Post to Slack if configured
      if (ctx.slack.isEnabled()) {
        const channel = ctx.config?.slack?.channels?.sales?.id || ctx.config?.slack?.channels?.ai_assistant?.id
        if (channel) {
          const text = lines.join('\n')
          const result = await ctx.slack.postMessage({ channel, text })
          summary.slack_posted = result.ok
          if (!result.ok) errors.push(`Slack post failed: ${result.error}`)
        }
      }

      events.push(buildEvent(this.id, 'run_summary', summary))
    } catch (err: any) {
      errors.push(err.message)
      summary.errors.push(err.message)
    }

    return { success: errors.length === 0, summary, errors, events }
  },
}
