import fs from 'fs'
import path from 'path'
import type { Agent, AgentContext, AgentResult } from './types.js'
import { readMasterSheet, readJSON, readJSONL, localDateStr } from './data.js'
import { buildEvent } from './logger.js'

export const qaHealth: Agent = {
  id: 'gc-qa-health',
  name: 'QA Health',

  async run(ctx: AgentContext): Promise<AgentResult> {
    const summary: Record<string, any> = { checked: 0, issues: 0, errors: [] }
    const events = []
    const errors: string[] = []
    const issues: string[] = []

    try {
      const leads = readMasterSheet(ctx.dataDir)
      const config = ctx.config
      const calls = readJSON(ctx.dataDir, 'today-calls.json')
      const eventLines = readJSONL(ctx.dataDir, 'agent-events.jsonl')

      summary.checked = leads.length

      // Integration health
      summary.integrations = {
        gmail: ctx.gmail.isEnabled(),
        calendar: ctx.calendar.isEnabled(),
        fireflies: ctx.fireflies.isEnabled(),
        slack: ctx.slack.isEnabled(),
        stripe: !!config?.stripe?.api_key,
      }

      if (!ctx.gmail.isEnabled()) issues.push('Gmail integration not configured')
      if (!ctx.fireflies.isEnabled()) issues.push('Fireflies integration not configured')

      // Missing emails
      const missingEmail = leads.filter((l: any) => !l.email)
      if (missingEmail.length > 0) issues.push(`${missingEmail.length} leads missing email`)

      // Duplicate emails
      const emails = leads.map((l: any) => l.email?.toLowerCase()).filter(Boolean)
      const dupes = emails.filter((e, i, a) => a.indexOf(e) !== i)
      if (dupes.length > 0) issues.push(`${new Set(dupes).size} duplicate email addresses`)

      // Leads stuck in booked with no call date
      const stuckBooked = leads.filter((l: any) => l.status === 'booked' && !l.next_call_date)
      if (stuckBooked.length > 0) issues.push(`${stuckBooked.length} booked leads with no call date`)

      // Stale events file (> 7 days old)
      const stats = fs.statSync(path.join(ctx.dataDir, 'agent-events.jsonl'))
      const daysSinceEvent = (ctx.now.getTime() - stats.mtime.getTime()) / 86400000
      if (daysSinceEvent > 7) issues.push(`agent-events.jsonl not updated in ${Math.round(daysSinceEvent)} days`)

      // Stale calls file (> 1 day old)
      if (calls?.generated_at) {
        const daysSinceCalls = (ctx.now.getTime() - new Date(calls.generated_at).getTime()) / 86400000
        if (daysSinceCalls > 1) issues.push(`today-calls.json is ${Math.round(daysSinceCalls)} days old`)
      }

      summary.issues = issues.length

      const todayStr = localDateStr(ctx.now, ctx.timezone)
      const lines = [
        `# QA Health Report — ${todayStr}`,
        '',
        `## Summary`,
        `- Records checked: ${summary.checked}`,
        `- Issues found: ${summary.issues}`,
        `- Status: ${issues.length === 0 ? '✅ Healthy' : '⚠️ Needs attention'}`,
        '',
        `## Integration Status`,
        `- Gmail: ${summary.integrations.gmail ? '✅' : '❌'}`,
        `- Google Calendar: ${summary.integrations.calendar ? '✅' : '❌'}`,
        `- Fireflies: ${summary.integrations.fireflies ? '✅' : '❌'}`,
        `- Slack: ${summary.integrations.slack ? '✅' : '❌'}`,
        `- Stripe: ${summary.integrations.stripe ? '✅' : '❌'}`,
        '',
        `## Issues`,
        ...(issues.length > 0 ? issues.map(i => `- ${i}`) : ['- No issues detected.']),
        '',
        `## Event Log Health`,
        `- Total events: ${eventLines.length}`,
        `- Last event: ${eventLines.length > 0 ? (eventLines[eventLines.length - 1] as any).ts : 'none'}`,
        '',
        `_Generated by ${this.name} at ${ctx.now.toISOString()}_`,
      ]

      const dir = path.join(ctx.dataDir, 'reports', 'daily')
      fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(path.join(dir, `${todayStr}-qa.md`), lines.join('\n'))

      events.push(buildEvent(this.id, 'run_summary', summary))
    } catch (err: any) {
      errors.push(err.message)
      summary.errors.push(err.message)
    }

    return { success: issues.length === 0, summary, errors, events }
  },
}
